general:
  # cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  # cfOrg: 'CGI_Technologies and Solutions Inc._ds-k49322hx5w2x0'
  # cfSpace: 'dev'
  # cfCredentialsId: 'cfAuthentification'
  host: '985d2012-0f3f-40b1-8d57-d12e1ec11b1b.abap.eu10.hana.ondemand.com'
  abapCredentialsId: 'abapCredentialsId'
  # cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  # cfOrg: 'CGI_Technologies and Solutions Inc._ds-k49322hx5w2x0'
  # cfSpace: 'dev'
  # cfCredentialsId: 'cfAuthentification'
  # cfServiceInstance: 'AbapPipeline'
  # cfServiceKeyName: 'sap_com_0510.json'

  
stages:
  # Prepare System:
  #   cfService: 'abap'
  #   cfServicePlan: 'standard'
  #   abapSystemAdminEmail: 'alex.tenin@cgi.com'
  #   abapSystemDescription: 'ABAP Environment Q System'
  #   abapSystemIsDevelopmentAllowed: true
  #   abapSystemID: 'H02'
  #   abapSystemSizeOfPersistence: 4
  #   abapSystemSizeOfRuntime: 1
  #   cfServiceKeyConfig: 'sap_com_0510.json'

  Clone Repositories:
      repositories: 'repositories.yml'
      strategy: 'Pull'
  ATC:
    atcConfig: 'atcConfig.yml'

    ##abap user= CC_USER
    ##abap pass = XRu>Ha9KEAGiLQnqpqceSQBburNTUgApjSXsKhbo
    ## host =985d2012-0f3f-40b1-8d57-d12e1ec11b1b.abap.eu10.hana.ondemand.com/sap/opu/odata/sap/MANAGE_GIT_REPOSITORY

steps:
 cloudFoundryDeleteService:
    cfDeleteServiceKeys: false