general:
  cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  cfOrg: '38f8e24e-106e-4fc8-bc13-48d06740411d'
  cfSpace: 'dev'
  cfCredentialsId: 'cfAuthentification'
  host: '49a2d9c8-2849-46e2-bf98-537e3437c07d.abap.eu10.hana.ondemand.com'
  abapCredentialsId: 'abapcred'

  
stages:
  Clone Repositories:
      repositories: 'repositories.yml'
      strategy: 'Clone'
  
  ATC:
    atcConfig: 'atcConfig.yml'

    ##abap user= CC_USER
    ##abap pass = hXRunjwHKiJF6feodfNUkJkqZygWSSfRTJEixL-e
