general:
  cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  cfOrg: '18d6e1batrial_3swc8q06zf9gdwpj'
  cfSpace: 'dev'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'default_abap-trial'
  cfServiceKeyName: 'jenkins_sap_com_0510'

stages:
  Prepare System:
    cfServiceInstance: 'default_abap-trial'
    cfService: 'abap'
    cfServicePlan: 'standard'
    email: 'shubhamr174@gmail.com'
  # Clone Repositories:
  #   strategy: 'clone'
  #   repositories: 'repositories.yml'
  # ATC:
  #   atcConfig: 'atcConfig.yml'
  Build:
    cfServiceKeyName: 'JENKINS_SAP_COM_0582'
    cfServiceKeyConfig: 'sap_com_0582.json'

